namespace: monitoring
targetCustomizations:
  - name: monitoring
    clusterSelector:
      matchLabels:
        cluster-role: management
    helm:
      releaseName: kube-prometheus-stack
      valuesFiles: 
        - values.yaml